{
	"version": 1733921683,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite5-sheet1.png",
		"images/sprite5-sheet2.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite7-sheet1.png",
		"images/sprite8-sheet0.png",
		"images/sprite8-sheet1.png",
		"images/sprite8-sheet2.png",
		"images/sprite9-sheet0.png",
		"images/tiledbackground2.png",
		"media/us. canada - bgm.m4a",
		"media/us. canada - bgm.ogg",
		"media/jt_0.m4a",
		"media/jt_0.ogg",
		"media/jt_1.m4a",
		"media/jt_1.ogg",
		"media/jt_2.m4a",
		"media/jt_2.ogg",
		"media/tr_0.m4a",
		"media/tr_0.ogg",
		"media/tr_1.m4a",
		"media/tr_1.ogg",
		"media/tr_2.m4a",
		"media/tr_2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}