{
	"version": 1733913894,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite5-sheet1.png",
		"images/sprite5-sheet2.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite7-sheet1.png",
		"images/sprite8-sheet0.png",
		"images/sprite8-sheet1.png",
		"images/sprite8-sheet2.png",
		"media/jt - may i.m4a",
		"media/jt - may i.ogg",
		"media/jt - opportunity.m4a",
		"media/jt - opportunity.ogg",
		"media/jt - you you.m4a",
		"media/jt - you you.ogg",
		"media/trump - nasty person.m4a",
		"media/trump - nasty person.ogg",
		"media/trump - thank you.m4a",
		"media/trump - thank you.ogg",
		"media/trump 5.m4a",
		"media/trump 5.ogg",
		"media/us. canada - bgm.m4a",
		"media/us. canada - bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}